import type { TranscriptSection } from "@/types/video";

const mockData: TranscriptSection[] = [
  {
    title: "React Core Concepts",
    sentences: [
      {
        id: "1",
        text: "In this video, I want to introduce you to React and go over the core concepts I think every React developer should aim to learn and master.",
        startTime: 0,
        endTime: 7,
        isHighlight: false,
      },
      {
        id: "2",
        text: "When it came to putting these concepts together, I selected them based on things you'll need to build out most of the functionality that you see in websites today and things somebody interviewing you would probably expect you to know.",
        startTime: 8,
        endTime: 19,
        isHighlight: false,
      },
      {
        id: "3",
        text: "But before we get started, I want to quickly mention my React crash course that's linked in the video description.",
        startTime: 19,
        endTime: 24,
        isHighlight: false,
      },
      {
        id: "4",
        text: "In this course, you will learn more about the concepts I mentioned here while building a fun notes application.",
        startTime: 24,
        endTime: 30,
        isHighlight: false,
      },
    ],
  },
  {
    title: "What is REACT?",
    sentences: [
      {
        id: "5",
        text: "So what is React?",
        startTime: 30,
        endTime: 31,
        isHighlight: false,
      },
      {
        id: "6",
        text: "React is a JavaScript library for building out user interfaces.",
        startTime: 32,
        endTime: 35,
        isHighlight: true,
      },
      {
        id: "7",
        text: "When you look at websites like Facebook, Netflix and Airbnb, you're looking at UIs built in React.",
        startTime: 36,
        endTime: 42,
        isHighlight: false,
      },
      {
        id: "8",
        text: "React provides us with a set of tools and structure for building out these user interfaces and makes this process much faster and easier.",
        startTime: 42,
        endTime: 49,
        isHighlight: true,
      },
    ],
  },
  {
    title: "Single Page Applications #1",
    sentences: [
      {
        id: "9",
        text: "Single page applications.",
        startTime: 51,
        endTime: 52,
        isHighlight: false,
      },
      {
        id: "10",
        text: "With React, it's very common to build out single page applications.",
        startTime: 53,
        endTime: 56,
        isHighlight: false,
      },
      {
        id: "11",
        text: "So before we get into the React concepts, I want to quickly recap single page applications and how they work for anybody that's not familiar with this concept yet.",
        startTime: 56,
        endTime: 64,
        isHighlight: false,
      },
      {
        id: "12",
        text: "So in traditional websites, we have a template for each page on our website and return that template back to the user whenever they request it.",
        startTime: 64,
        endTime: 71,
        isHighlight: false,
      },
      {
        id: "13",
        text: "With single page applications, however, we are working with one single template and are simply updating all the components within the DOM.",
        startTime: 72,
        endTime: 78,
        isHighlight: true,
      },
      {
        id: "14",
        text: "Personally, I think the term single page application is a bit misleading as it makes me think there is only one page in our application, when really we're just using one single template and modifying all the content within it.",
        startTime: 79,
        endTime: 90,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Components #2",
    sentences: [
      {
        id: "15",
        text: "Components are what make up the visual layer of our application and let us split up our UI into independent reusable pieces.",
        startTime: 91,
        endTime: 98,
        isHighlight: true,
      },
      {
        id: "16",
        text: "While how you build and structure your application is completely up to you, traditionally, each part of our UI would be built out separately as its own component and then added into a parent component making up the UI for a specific page.",
        startTime: 98,
        endTime: 111,
        isHighlight: false,
      },
      {
        id: "17",
        text: "A component is a JavaScript class or function that returns back some HTML.",
        startTime: 111,
        endTime: 115,
        isHighlight: true,
      },
      {
        id: "18",
        text: "Well, this is actually something called JSX, but more on that in a second.",
        startTime: 116,
        endTime: 119,
        isHighlight: false,
      },
      {
        id: "19",
        text: "One thing to note about components is that they can be nested as deep as you want.",
        startTime: 120,
        endTime: 123,
        isHighlight: false,
      },
      {
        id: "20",
        text: "A component can hold another component and that component can hold more components.",
        startTime: 124,
        endTime: 128,
        isHighlight: false,
      },
      {
        id: "21",
        text: "While I do think you should learn both class-based components and function-based components at some point, with the addition of React hooks, the trend is shifting more towards using functional components.",
        startTime: 128,
        endTime: 138,
        isHighlight: false,
      },
      {
        id: "22",
        text: "So if you're trying to decide which to learn first, you can probably start with functional components.",
        startTime: 138,
        endTime: 142,
        isHighlight: false,
      },
    ],
  },
  {
    title: "JSX #3",
    sentences: [
      {
        id: "23",
        text: "JSX.",
        startTime: 144,
        endTime: 145,
        isHighlight: false,
      },
      {
        id: "24",
        text: "Instead of writing traditional HTML tags, we're going to be using something called JSX which stands for JavaScript XML.",
        startTime: 146,
        endTime: 152,
        isHighlight: true,
      },
      {
        id: "25",
        text: "JSX actually looks a lot like HTML with some slight syntax differences and also gives us some added functionality.",
        startTime: 153,
        endTime: 159,
        isHighlight: false,
      },
      {
        id: "26",
        text: "Take a look at this example and you'll see how you can use the curly braces to pass in variables and adding JavaScript logic directly into your HTML.",
        startTime: 159,
        endTime: 167,
        isHighlight: true,
      },
      {
        id: "27",
        text: "JSX tags are actually very similar to HTML tags.",
        startTime: 168,
        endTime: 171,
        isHighlight: false,
      },
      {
        id: "28",
        text: "Some notable differences are things like class declarations which are written as class name and how event handlers are added.",
        startTime: 172,
        endTime: 178,
        isHighlight: false,
      },
      {
        id: "29",
        text: "Browsers can't actually read JSX, so this code will actually be run through a compiler and converted into traditional HTML and JavaScript code once it's output in the browser.",
        startTime: 179,
        endTime: 188,
        isHighlight: true,
      },
    ],
  },
  {
    title: "URL Routing #4",
    sentences: [
      {
        id: "30",
        text: "React router.",
        startTime: 189,
        endTime: 190,
        isHighlight: false,
      },
      {
        id: "31",
        text: "Using a React router is how we can have multiple pages in a single page application.",
        startTime: 190,
        endTime: 195,
        isHighlight: true,
      },
      {
        id: "32",
        text: "With React, we typically handle URL routing with something called a router that keeps our UI in sync with a URL.",
        startTime: 195,
        endTime: 201,
        isHighlight: false,
      },
      {
        id: "33",
        text: "Because we're not actually changing pages, the router will take care of rendering out components into the DOM based on the current URL.",
        startTime: 202,
        endTime: 208,
        isHighlight: true,
      },
    ],
  },
  {
    title: "Props #5",
    sentences: [
      {
        id: "34",
        text: "Props.",
        startTime: 209,
        endTime: 210,
        isHighlight: false,
      },
      {
        id: "35",
        text: "When you need to pass data down from one component to another, you can pass it down as a prop.",
        startTime: 211,
        endTime: 215,
        isHighlight: true,
      },
      {
        id: "36",
        text: "A prop can be passed down like a function parameter.",
        startTime: 216,
        endTime: 219,
        isHighlight: false,
      },
      {
        id: "37",
        text: "Once a prop is passed down into a component, you can now use that prop anywhere in the child component.",
        startTime: 219,
        endTime: 224,
        isHighlight: false,
      },
      {
        id: "38",
        text: "Props can be passed down multiple layers if needed.",
        startTime: 225,
        endTime: 227,
        isHighlight: false,
      },
      {
        id: "39",
        text: "The term for this is called prop drilling.",
        startTime: 228,
        endTime: 229,
        isHighlight: true,
      },
      {
        id: "40",
        text: "Prop drilling can get messy, so we'll talk about some solutions to this in a minute.",
        startTime: 230,
        endTime: 233,
        isHighlight: false,
      },
    ],
  },
  {
    title: "State #6",
    sentences: [
      {
        id: "41",
        text: "State.",
        startTime: 234,
        endTime: 235,
        isHighlight: false,
      },
      {
        id: "42",
        text: "State is simply a JavaScript object used to represent information in or about a particular component.",
        startTime: 236,
        endTime: 241,
        isHighlight: true,
      },
      {
        id: "43",
        text: "Traditionally, we use class-based components to set our state and its values, but more modernly, we use React hooks like use state to create a component state.",
        startTime: 242,
        endTime: 250,
        isHighlight: true,
      },
      {
        id: "44",
        text: "So let's imagine for a second that we have a list of notes that we want to render out in our app.",
        startTime: 251,
        endTime: 255,
        isHighlight: false,
      },
      {
        id: "45",
        text: "We can set an initial state and then map through that state and output all that data in our component.",
        startTime: 256,
        endTime: 261,
        isHighlight: false,
      },
      {
        id: "46",
        text: "We can also update our state.",
        startTime: 261,
        endTime: 262,
        isHighlight: false,
      },
      {
        id: "47",
        text: "In this example, we can set our initial state as an empty array, then we request some data from our API and update that state with new data.",
        startTime: 263,
        endTime: 270,
        isHighlight: false,
      },
      {
        id: "48",
        text: "This state update will trigger our component lifecycle effect, which we'll talk about next.",
        startTime: 271,
        endTime: 275,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Component Lifecycle #7",
    sentences: [
      {
        id: "49",
        text: "the component life cycle.",
        startTime: 275,
        endTime: 277,
        isHighlight: false,
      },
      {
        id: "50",
        text: "Understanding the component life cycle is a must for every react developer and is probably one of the most common interview questions for junior developers.",
        startTime: 278,
        endTime: 286,
        isHighlight: true,
      },
      {
        id: "51",
        text: "A React component has a life cycle that it goes through and there are three main phases that we need to know about in this life cycle.",
        startTime: 286,
        endTime: 292,
        isHighlight: false,
      },
      {
        id: "52",
        text: "Each component has a mounting phase for when it's first being added to the DOM, an updating phase for when we are modifying something and that component needs to update, and an unmounting phase for when this component will be removed from the DOM.",
        startTime: 293,
        endTime: 306,
        isHighlight: true,
      },
      {
        id: "53",
        text: "With class components, we have these three methods to take care of these lifecycle methods.",
        startTime: 306,
        endTime: 310,
        isHighlight: false,
      },
      {
        id: "54",
        text: "We have component did mount, component did update, and component will unmount.",
        startTime: 311,
        endTime: 316,
        isHighlight: false,
      },
      {
        id: "55",
        text: "With functional components, however, we have a method called use effect that allows us to work with each part of a component life cycle.",
        startTime: 316,
        endTime: 322,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Hooks #8",
    sentences: [
      {
        id: "56",
        text: "React hooks.",
        startTime: 323,
        endTime: 324,
        isHighlight: false,
      },
      {
        id: "57",
        text: "React hooks only apply to functional components, but due to the popularity of using function-based components, hooks have become essential to learn in this process.",
        startTime: 325,
        endTime: 332,
        isHighlight: false,
      },
      {
        id: "58",
        text: "Hooks let us add state and other features without using class-based components.",
        startTime: 333,
        endTime: 337,
        isHighlight: true,
      },
      {
        id: "59",
        text: "Before hooks, functional components could not hold any state.",
        startTime: 337,
        endTime: 340,
        isHighlight: false,
      },
      {
        id: "60",
        text: "Hooks are simply functions that allow us to hook into and manage state.",
        startTime: 341,
        endTime: 345,
        isHighlight: true,
      },
      {
        id: "61",
        text: "The two most common hooks that you'll probably use when you first start are going to be use state, which lets us set and update our state in a component and use effect that is simply a function that allows us to manage our component life cycle.",
        startTime: 347,
        endTime: 358,
        isHighlight: true,
      },
      {
        id: "62",
        text: "React gives us a whole list of built-in hooks along with the ability to create our own custom hooks.",
        startTime: 359,
        endTime: 364,
        isHighlight: false,
      },
    ],
  },
  {
    title: "State Management #9",
    sentences: [
      {
        id: "63",
        text: "State management.",
        startTime: 365,
        endTime: 366,
        isHighlight: false,
      },
      {
        id: "64",
        text: "While we can create and manage state inside of our component, there will likely be a time when we need to create some form of global state to make data available across multiple components.",
        startTime: 367,
        endTime: 376,
        isHighlight: true,
      },
      {
        id: "65",
        text: "Think of something like holding data for a logged-in user.",
        startTime: 377,
        endTime: 379,
        isHighlight: false,
      },
      {
        id: "66",
        text: "You may need this user across multiple components like your header bar or a profile component, and passing this data down through props may not be practical, especially when this information is updated somewhere inside of those components.",
        startTime: 380,
        endTime: 392,
        isHighlight: false,
      },
      {
        id: "67",
        text: "We have several options to handle this, like using the built-in context API or using a third-party package like Redux and many others out there.",
        startTime: 393,
        endTime: 400,
        isHighlight: true,
      },
      {
        id: "68",
        text: "With these, we are able to create some form of global state and use it across multiple components in our component tree without having to deal with prop drilling.",
        startTime: 401,
        endTime: 409,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Virtual DOM #10",
    sentences: [
      {
        id: "69",
        text: "The virtual DOM.",
        startTime: 410,
        endTime: 411,
        isHighlight: false,
      },
      {
        id: "70",
        text: "At some point in the process of learning React, you will want to have an understanding of how the virtual DOM works.",
        startTime: 412,
        endTime: 416,
        isHighlight: false,
      },
      {
        id: "71",
        text: "Understanding this will help you understand and make sense of how React builds and updates our DOM and the complete lifecycle of a React component.",
        startTime: 417,
        endTime: 424,
        isHighlight: false,
      },
      {
        id: "72",
        text: "In short, React creates something called the virtual DOM, which is a virtual representation of the real DOM.",
        startTime: 425,
        endTime: 430,
        isHighlight: true,
      },
      {
        id: "73",
        text: "When we're updating our components, we're actually updating the virtual DOM and not the real DOM.",
        startTime: 430,
        endTime: 435,
        isHighlight: false,
      },
      {
        id: "74",
        text: "Using this method, React can find the most efficient way to update the real DOM by updating only areas where changes have been made without having to update the entire DOM.",
        startTime: 435,
        endTime: 444,
        isHighlight: true,
      },
    ],
  },
  {
    title: "Key Prop #11",
    sentences: [
      {
        id: "75",
        text: "the key prop.",
        startTime: 445,
        endTime: 446,
        isHighlight: false,
      },
      {
        id: "76",
        text: "When it comes to rendering out a list of data in your component, there is one thing you should be aware of, and that is the key prop.",
        startTime: 447,
        endTime: 453,
        isHighlight: false,
      },
      {
        id: "77",
        text: "Each item in a dynamically rendered list should contain the key prop, or else you'll get this annoying error in the console.",
        startTime: 453,
        endTime: 459,
        isHighlight: true,
      },
      {
        id: "78",
        text: "This prop should be unique and helps React identify which items have been changed, added or removed, so React knows which part of the virtual DOM to update.",
        startTime: 460,
        endTime: 468,
        isHighlight: true,
      },
    ],
  },
  {
    title: "Event Listeners #12",
    sentences: [
      {
        id: "79",
        text: "Event listeners.",
        startTime: 469,
        endTime: 470,
        isHighlight: false,
      },
      {
        id: "80",
        text: "Handling events with React is very similar to how we would do this in traditional JavaScript with a few differences.",
        startTime: 471,
        endTime: 476,
        isHighlight: false,
      },
      {
        id: "81",
        text: "In React, we camel case event names and we pass the function we want to call directly in line between two curly braces.",
        startTime: 477,
        endTime: 483,
        isHighlight: true,
      },
      {
        id: "82",
        text: "So there is no need for methods like add event listener because our JavaScript code and HTML are mixed together.",
        startTime: 483,
        endTime: 489,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Forms #13",
    sentences: [
      {
        id: "83",
        text: "Handling forms.",
        startTime: 490,
        endTime: 491,
        isHighlight: false,
      },
      {
        id: "84",
        text: "With React, how we handle forms is a little bit different from the traditional method because we are trying to keep all our information in some form of state inside of our component.",
        startTime: 492,
        endTime: 500,
        isHighlight: true,
      },
      {
        id: "85",
        text: "HTML elements such as input, text area and select typically maintain their own state and update based on a user's input.",
        startTime: 501,
        endTime: 508,
        isHighlight: false,
      },
      {
        id: "86",
        text: "With React, however, we typically add event listeners to each field and update our component state whenever any one of these inputs change.",
        startTime: 509,
        endTime: 516,
        isHighlight: true,
      },
      {
        id: "87",
        text: "So methods like on change and on submit would directly update our state and would be controlled by our own functions instead of letting the form handle all of this on its own.",
        startTime: 516,
        endTime: 525,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Conditional Rendering #14",
    sentences: [
      {
        id: "88",
        text: "conditional rendering.",
        startTime: 526,
        endTime: 527,
        isHighlight: false,
      },
      {
        id: "89",
        text: "There is always a chance that you will need to render out some content conditionally depending on other values inside of your application.",
        startTime: 527,
        endTime: 534,
        isHighlight: true,
      },
      {
        id: "90",
        text: "Think of something like a user's name inside of a navigation bar.",
        startTime: 534,
        endTime: 537,
        isHighlight: false,
      },
      {
        id: "91",
        text: "Depending on the user's authentication status, you will either display the user's name or display nothing.",
        startTime: 538,
        endTime: 543,
        isHighlight: false,
      },
      {
        id: "92",
        text: "One way we can go about handling this is using the logical and operator.",
        startTime: 544,
        endTime: 547,
        isHighlight: false,
      },
      {
        id: "93",
        text: "We can also use the inline if else conditional operator if we want to add in some extra logic.",
        startTime: 548,
        endTime: 553,
        isHighlight: false,
      },
      {
        id: "94",
        text: "In both of these examples, the rendered output will depend on the conditions we provide.",
        startTime: 553,
        endTime: 557,
        isHighlight: false,
      },
    ],
  },
  {
    title: "Commands #15",
    sentences: [
      {
        id: "95",
        text: "Common commands.",
        startTime: 558,
        endTime: 559,
        isHighlight: false,
      },
      {
        id: "96",
        text: "There are three main commands I want to mention here because these are commands you will use in every project.",
        startTime: 560,
        endTime: 564,
        isHighlight: false,
      },
      {
        id: "97",
        text: "We have the create React app command, which creates the boiler plate files for a React application.",
        startTime: 565,
        endTime: 570,
        isHighlight: true,
      },
      {
        id: "98",
        text: "We have the start command that starts up our development server so we can view our project right away.",
        startTime: 570,
        endTime: 575,
        isHighlight: true,
      },
      {
        id: "99",
        text: "And we have the run build command that builds a directory for a production build of our app for deployment.",
        startTime: 575,
        endTime: 581,
        isHighlight: true,
      },
      {
        id: "100",
        text: "All right, so that's my list of core concepts every React developer should master.",
        startTime: 581,
        endTime: 585,
        isHighlight: false,
      },
      {
        id: "101",
        text: "Don't forget to subscribe if you enjoyed this video and make sure to check out the React crash course linked in the video description if you want to learn more.",
        startTime: 585,
        endTime: 593,
        isHighlight: false,
      },
    ],
  },
];

export default mockData;
